### ISSUE TITLE
Problem with account creation

### ISSUE THREAD

**Issue by cupidare** [gburton/CE-Phoenix#943]
I don't know whether it is a problem just with the test site https://template.me.uk/phoenix/create_account.php : 

When attempting to create an account on the official test site I encountered the following error:

![image](https://user-images.githubusercontent.com/22186911/77730227-aa700380-7000-11ea-9c84-a3f8a2f65218.png)

It seems there is no pull-down menu.

I was wondering whether I would receive also a confirmation mail after placing a order where the characters in all of the addresses of just the confirmation mail are not correctly utf-8 converted (like on my installation).

**Comment by gburton** [comment]
Looks like when a country is input that has states, but a "not matching state" (eg a typo) is inserted (eg US and "FORLIDA"), the page reloads with that message.  But the states dropdown does not appear.  Hopefully Matt can have a look to check on one of his installs as it seems to be somewhere in the new Customer Data modules...

**Comment by ecartz** [comment]
This should be fixed in the (now live) 1.0.5.6 release.

**Comment by gburton** [comment]
@cupidare please test the update...TY

**Comment by cupidare** [comment]
Now it works well on a fresh install of 1.0.5.7 - but still not at template.me.uk

BUT

- still the same problem in address_book_process.php when adding a new address
- not able to add a different/new address in checkout_shipping_address.php
- not able to add a different/new address in /checkout_payment_address.php

**Comment by ecartz** [comment]
I have no problems adding a new address in checkout in 1.0.5.7.  But if I put in an incorrect value, it wasn't messaging it properly.  Should be fixed in the current code (that will be 1.0.5.8).

**Comment by cupidare** [comment]
seems to be working now at least for my test settings
